# Use postgres/example user/password credentials
version: '3.1'
#https://hub.docker.com/_/postgres/
services:

  db:
    image: postgres
    restart: always
    ports: 
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
